"""Initial migration

Revision ID: e6945cbd3c1d
Revises: 
Create Date: 2025-11-08 13:00:40.715978

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision = 'e6945cbd3c1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gen_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='작업 ID'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='프로젝트 외래키'),
    sa.Column('job_type', sa.String(length=100), nullable=False, comment='작업 타입'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='작업 상태'),
    sa.Column('result', sa.Text(), nullable=True, comment='생성 결과 (CLOB)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성 시간'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정 시간'),
    sa.CheckConstraint("job_type IN ('code_generation', 'document_generation', 'test_generation', 'refactoring')", name='chk_gen_job_type'),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed', 'cancelled')", name='chk_gen_job_status'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='버전 ID'),
    sa.Column('document_id', sa.Integer(), nullable=False, comment='문서 외래키'),
    sa.Column('version_number', sa.Integer(), nullable=False, comment='버전 번호'),
    sa.Column('content', sa.Text(), nullable=False, comment='버전별 문서 내용 (CLOB)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='버전 생성 시간'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='링크 ID'),
    sa.Column('parent_task_id', sa.Integer(), nullable=False, comment='부모 태스크 ID'),
    sa.Column('child_task_id', sa.Integer(), nullable=False, comment='자식 태스크 ID'),
    sa.Column('link_type', sa.String(length=50), nullable=False, comment='링크 타입'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성 시간'),
    sa.CheckConstraint("link_type IN ('blocks', 'depends_on', 'relates_to')", name='chk_task_link_type'),
    sa.CheckConstraint('parent_task_id != child_task_id', name='chk_no_self_link'),
    sa.ForeignKeyConstraint(['child_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_mcp_run_events_run'), table_name='mcp_run_events')
    op.drop_table('mcp_run_events')
    op.drop_index(op.f('ix_mcp_conn_project'), table_name='mcp_connections')
    op.drop_index(op.f('ix_mcp_conn_status'), table_name='mcp_connections')
    op.drop_table('mcp_connections')
    op.drop_index(op.f('ix_chat_sessions_created_at'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_doc'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_user'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_mcp_runs_mode'), table_name='mcp_runs')
    op.drop_index(op.f('ix_mcp_runs_session'), table_name='mcp_runs')
    op.drop_index(op.f('ix_mcp_runs_status'), table_name='mcp_runs')
    op.drop_table('mcp_runs')
    op.drop_index(op.f('sys_c007624'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_chat_messages_session'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_created'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_mcp_sess_conn'), table_name='mcp_sessions')
    op.drop_index(op.f('ix_mcp_sess_project'), table_name='mcp_sessions')
    op.drop_index(op.f('ix_mcp_sess_status'), table_name='mcp_sessions')
    op.drop_table('mcp_sessions')
    op.add_column('documents', sa.Column('content', sa.Text(), nullable=True, comment='문서 내용 (CLOB)'))
    op.add_column('documents', sa.Column('doc_type', sa.String(length=50), nullable=False, comment='문서 타입'))
    op.alter_column('documents', 'id',
               existing_type=oracle.NUMBER(asdecimal=False),
               server_default=None,
               comment='문서 고유 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('documents', 'project_id',
               existing_type=oracle.NUMBER(asdecimal=False),
               comment='프로젝트 외래키',
               existing_nullable=False)
    op.alter_column('documents', 'title',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               comment='문서 제목',
               existing_nullable=False)
    op.alter_column('documents', 'created_at',
               existing_type=oracle.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               comment='생성 시간',
               existing_nullable=False,
               existing_server_default=sa.text('SYSTIMESTAMP '))
    op.alter_column('documents', 'updated_at',
               existing_type=oracle.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               comment='수정 시간')
    op.drop_index(op.f('ix_documents_project_type'), table_name='documents')
    op.drop_index(op.f('uq_documents_project_title'), table_name='documents')
    op.drop_column('documents', 'author_id')
    op.drop_column('documents', 'last_editor_id')
    op.drop_column('documents', 'content_md')
    op.drop_column('documents', 'type')
    op.alter_column('projects', 'id',
               existing_type=oracle.NUMBER(asdecimal=False),
               server_default=None,
               comment='프로젝트 고유 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('projects', 'project_idx',
               existing_type=oracle.NUMBER(asdecimal=False),
               nullable=False,
               comment='user별 프로젝트 idx')
    op.alter_column('projects', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment='프로젝트 제목',
               existing_nullable=False)
    op.alter_column('projects', 'content_md',
               existing_type=sa.CLOB(),
               type_=sa.String(),
               comment='프로젝트 내용',
               existing_nullable=True)
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=30),
               comment='프로젝트 상태',
               existing_nullable=False,
               existing_server_default=sa.text("'in_progress' "))
    op.alter_column('projects', 'owner_id',
               existing_type=sa.VARCHAR(length=120),
               comment='프로젝트 소유자',
               existing_nullable=True)
    op.alter_column('projects', 'created_at',
               existing_type=oracle.TIMESTAMP(timezone=True),
               type_=sa.DateTime(timezone=True),
               comment='생성 시간',
               existing_nullable=False,
               existing_server_default=sa.text('SYSTIMESTAMP '))
    op.alter_column('projects', 'updated_at',
               existing_type=oracle.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               comment='수정 시간',
               existing_nullable=True)
    op.drop_index(op.f('ix_projects_owner'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.add_column('tasks', sa.Column('description', sa.Text(), nullable=True, comment='태스크 설명 (CLOB)'))
    op.alter_column('tasks', 'id',
               existing_type=oracle.NUMBER(asdecimal=False),
               server_default=None,
               comment='태스크 ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('tasks', 'project_id',
               existing_type=oracle.NUMBER(asdecimal=False),
               comment='프로젝트 외래키',
               existing_nullable=False)
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               comment='태스크 제목',
               existing_nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               comment='태스크 상태',
               existing_nullable=False,
               existing_server_default=sa.text("'todo' "))
    op.alter_column('tasks', 'priority',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               comment='우선순위',
               existing_nullable=False,
               existing_server_default=sa.text("'medium' "))
    op.alter_column('tasks', 'created_at',
               existing_type=oracle.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               comment='생성 시간',
               existing_nullable=False,
               existing_server_default=sa.text('SYSTIMESTAMP '))
    op.alter_column('tasks', 'updated_at',
               existing_type=oracle.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               comment='수정 시간')
    op.drop_index(op.f('ix_tasks_due'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_source'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_column('tasks', 'type')
    op.drop_column('tasks', 'due_at')
    op.drop_column('tasks', 'assignee_id')
    op.drop_column('tasks', 'description_md')
    op.drop_column('tasks', 'source')
    op.drop_column('tasks', 'version')
    op.drop_column('tasks', 'tags')
    op.drop_column('tasks', 'reporter_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('reporter_id', sa.VARCHAR(length=120), nullable=True))
    op.add_column('tasks', sa.Column('tags', sa.VARCHAR(length=500), nullable=True))
    op.add_column('tasks', sa.Column('version', oracle.NUMBER(asdecimal=False), server_default=sa.text('1 '), nullable=False))
    op.add_column('tasks', sa.Column('source', sa.VARCHAR(length=10), server_default=sa.text("'manual' "), nullable=False))
    op.add_column('tasks', sa.Column('description_md', sa.CLOB(), nullable=True))
    op.add_column('tasks', sa.Column('assignee_id', sa.VARCHAR(length=120), nullable=True))
    op.add_column('tasks', sa.Column('due_at', oracle.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('type', sa.VARCHAR(length=10), server_default=sa.text("'feat' "), nullable=False))
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_source'), 'tasks', ['source'], unique=False)
    op.create_index(op.f('ix_tasks_project'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_due'), 'tasks', [sa.literal_column('SYS_EXTRACT_UTC("DUE_AT")')], unique=False)
    op.alter_column('tasks', 'updated_at',
               existing_type=sa.DateTime(),
               type_=oracle.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='수정 시간')
    op.alter_column('tasks', 'created_at',
               existing_type=sa.DateTime(),
               type_=oracle.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성 시간',
               existing_nullable=False,
               existing_server_default=sa.text('SYSTIMESTAMP '))
    op.alter_column('tasks', 'priority',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='우선순위',
               existing_nullable=False,
               existing_server_default=sa.text("'medium' "))
    op.alter_column('tasks', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='태스크 상태',
               existing_nullable=False,
               existing_server_default=sa.text("'todo' "))
    op.alter_column('tasks', 'title',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='태스크 제목',
               existing_nullable=False)
    op.alter_column('tasks', 'project_id',
               existing_type=oracle.NUMBER(asdecimal=False),
               comment=None,
               existing_comment='프로젝트 외래키',
               existing_nullable=False)
    op.alter_column('tasks', 'id',
               existing_type=oracle.NUMBER(asdecimal=False),
               server_default=sa.Identity(always=False, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False),
               comment=None,
               existing_comment='태스크 ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('tasks', 'description')
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_owner'), 'projects', ['owner_id'], unique=False)
    op.alter_column('projects', 'updated_at',
               existing_type=sa.DateTime(),
               type_=oracle.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='수정 시간',
               existing_nullable=True)
    op.alter_column('projects', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=oracle.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성 시간',
               existing_nullable=False,
               existing_server_default=sa.text('SYSTIMESTAMP '))
    op.alter_column('projects', 'owner_id',
               existing_type=sa.VARCHAR(length=120),
               comment=None,
               existing_comment='프로젝트 소유자',
               existing_nullable=True)
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='프로젝트 상태',
               existing_nullable=False,
               existing_server_default=sa.text("'in_progress' "))
    op.alter_column('projects', 'content_md',
               existing_type=sa.String(),
               type_=sa.CLOB(),
               comment=None,
               existing_comment='프로젝트 내용',
               existing_nullable=True)
    op.alter_column('projects', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='프로젝트 제목',
               existing_nullable=False)
    op.alter_column('projects', 'project_idx',
               existing_type=oracle.NUMBER(asdecimal=False),
               nullable=True,
               comment=None,
               existing_comment='user별 프로젝트 idx')
    op.alter_column('projects', 'id',
               existing_type=oracle.NUMBER(asdecimal=False),
               server_default=sa.Identity(always=False, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False),
               comment=None,
               existing_comment='프로젝트 고유 ID',
               existing_nullable=False,
               autoincrement=True)
    op.add_column('documents', sa.Column('type', sa.VARCHAR(length=20), nullable=False))
    op.add_column('documents', sa.Column('content_md', sa.CLOB(), nullable=True))
    op.add_column('documents', sa.Column('last_editor_id', sa.VARCHAR(length=120), nullable=True))
    op.add_column('documents', sa.Column('author_id', sa.VARCHAR(length=120), nullable=True))
    op.create_index(op.f('uq_documents_project_title'), 'documents', ['project_id', 'title'], unique=True)
    op.create_index(op.f('ix_documents_project_type'), 'documents', ['project_id', 'type'], unique=False)
    op.alter_column('documents', 'updated_at',
               existing_type=sa.DateTime(),
               type_=oracle.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='수정 시간')
    op.alter_column('documents', 'created_at',
               existing_type=sa.DateTime(),
               type_=oracle.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성 시간',
               existing_nullable=False,
               existing_server_default=sa.text('SYSTIMESTAMP '))
    op.alter_column('documents', 'title',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               comment=None,
               existing_comment='문서 제목',
               existing_nullable=False)
    op.alter_column('documents', 'project_id',
               existing_type=oracle.NUMBER(asdecimal=False),
               comment=None,
               existing_comment='프로젝트 외래키',
               existing_nullable=False)
    op.alter_column('documents', 'id',
               existing_type=oracle.NUMBER(asdecimal=False),
               server_default=sa.Identity(always=False, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False),
               comment=None,
               existing_comment='문서 고유 ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('documents', 'doc_type')
    op.drop_column('documents', 'content')
    op.create_table('mcp_sessions',
    sa.Column('id', oracle.NUMBER(asdecimal=False), sa.Identity(always=False, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False), nullable=False),
    sa.Column('connection_id', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('project_id', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=120), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'ready' "), nullable=False),
    sa.Column('metadata', sa.CLOB(), nullable=True),
    sa.Column('created_at', oracle.TIMESTAMP(timezone=True), server_default=sa.text('SYSTIMESTAMP '), nullable=False),
    sa.Column('closed_at', oracle.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('ready','closed')", name='ck_mcp_sess_status'),
    sa.ForeignKeyConstraint(['connection_id'], ['mcp_connections.id'], name='fk_mcp_sess_conn', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_mcp_sess_project', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sys_c007681'),
    oracle_resolve_synonyms=False,
    oracle_tablespace='USERS'
    )
    op.create_index(op.f('ix_mcp_sess_status'), 'mcp_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_mcp_sess_project'), 'mcp_sessions', ['project_id'], unique=False)
    op.create_index(op.f('ix_mcp_sess_conn'), 'mcp_sessions', ['connection_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', oracle.NUMBER(asdecimal=False), sa.Identity(always=False, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False), nullable=False),
    sa.Column('session_id', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=120), nullable=True),
    sa.Column('content', sa.CLOB(), nullable=True),
    sa.Column('tool_calls_json', sa.CLOB(), nullable=True),
    sa.Column('created_at', oracle.TIMESTAMP(timezone=True), server_default=sa.text('SYSTIMESTAMP '), nullable=False),
    sa.CheckConstraint("role IN ('user','assistant','system','tool')", name=op.f('ck_chat_messages_role')),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('fk_chat_messages_session'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_c007649')),
    oracle_tablespace='USERS'
    )
    op.create_index(op.f('ix_chat_messages_session_created'), 'chat_messages', ['session_id', sa.literal_column('SYS_EXTRACT_UTC("CREATED_AT")')], unique=False)
    op.create_index(op.f('ix_chat_messages_session'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.VARCHAR(length=120), nullable=False),
    sa.Column('email', sa.VARCHAR(length=320), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', oracle.TIMESTAMP(timezone=True), server_default=sa.text('SYSTIMESTAMP '), nullable=False),
    sa.Column('updated_at', oracle.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('sys_c007623')),
    oracle_tablespace='USERS'
    )
    op.create_index(op.f('sys_c007624'), 'users', ['email'], unique=True)
    op.create_table('mcp_runs',
    sa.Column('id', oracle.NUMBER(asdecimal=False), sa.Identity(always=False, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False), nullable=False),
    sa.Column('session_id', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('run_mode', sa.VARCHAR(length=10), nullable=False),
    sa.Column('tool_id', sa.VARCHAR(length=120), nullable=True),
    sa.Column('prompt_id', sa.VARCHAR(length=120), nullable=True),
    sa.Column('config_json', sa.CLOB(), nullable=True),
    sa.Column('input_json', sa.CLOB(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'queued' "), nullable=False),
    sa.Column('output_json', sa.CLOB(), nullable=True),
    sa.Column('error_json', sa.CLOB(), nullable=True),
    sa.Column('started_at', oracle.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finished_at', oracle.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', oracle.TIMESTAMP(timezone=True), server_default=sa.text('SYSTIMESTAMP '), nullable=False),
    sa.CheckConstraint("run_mode IN ('chat','tool','prompt')", name='ck_mcp_runs_run_mode'),
    sa.CheckConstraint("status IN ('queued','running','succeeded','failed','cancelled')", name='ck_mcp_runs_status'),
    sa.ForeignKeyConstraint(['session_id'], ['mcp_sessions.id'], name='fk_mcp_runs_session', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sys_c007690'),
    oracle_resolve_synonyms=False,
    oracle_tablespace='USERS'
    )
    op.create_index(op.f('ix_mcp_runs_status'), 'mcp_runs', ['status'], unique=False)
    op.create_index(op.f('ix_mcp_runs_session'), 'mcp_runs', ['session_id'], unique=False)
    op.create_index(op.f('ix_mcp_runs_mode'), 'mcp_runs', ['run_mode'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', oracle.NUMBER(asdecimal=False), sa.Identity(always=False, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False), nullable=False),
    sa.Column('doc_id', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=120), nullable=True),
    sa.Column('created_at', oracle.TIMESTAMP(timezone=True), server_default=sa.text('SYSTIMESTAMP '), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], name=op.f('fk_chat_sessions_doc'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_c007643')),
    oracle_tablespace='USERS'
    )
    op.create_index(op.f('ix_chat_sessions_user'), 'chat_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_doc'), 'chat_sessions', ['doc_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_created_at'), 'chat_sessions', [sa.literal_column('SYS_EXTRACT_UTC("CREATED_AT")')], unique=False)
    op.create_table('mcp_connections',
    sa.Column('id', oracle.NUMBER(asdecimal=False), sa.Identity(always=False, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False), nullable=False),
    sa.Column('provider_id', sa.VARCHAR(length=40), nullable=False),
    sa.Column('project_id', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('workspace', sa.VARCHAR(length=500), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'connected' "), nullable=False),
    sa.Column('created_at', oracle.TIMESTAMP(timezone=True), server_default=sa.text('SYSTIMESTAMP '), nullable=False),
    sa.Column('closed_at', oracle.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('connected','closed')", name='ck_mcp_conn_status'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_mcp_conn_project', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sys_c007673'),
    oracle_resolve_synonyms=False,
    oracle_tablespace='USERS'
    )
    op.create_index(op.f('ix_mcp_conn_status'), 'mcp_connections', ['status'], unique=False)
    op.create_index(op.f('ix_mcp_conn_project'), 'mcp_connections', ['project_id'], unique=False)
    op.create_table('mcp_run_events',
    sa.Column('id', oracle.NUMBER(asdecimal=False), sa.Identity(always=False, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False), nullable=False),
    sa.Column('run_id', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=40), nullable=False),
    sa.Column('payload', sa.CLOB(), nullable=True),
    sa.Column('created_at', oracle.TIMESTAMP(timezone=True), server_default=sa.text('SYSTIMESTAMP '), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['mcp_runs.id'], name=op.f('fk_mcp_run_events_run'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sys_c007698')),
    oracle_tablespace='USERS'
    )
    op.create_index(op.f('ix_mcp_run_events_run'), 'mcp_run_events', ['run_id'], unique=False)
    op.drop_table('task_links')
    op.drop_table('document_versions')
    op.drop_table('gen_jobs')
    # ### end Alembic commands ###

